// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoj5K9FsCMTsOOBlMQXjPHeIR-IPZxJIM',
    appId: '1:437896099955:web:019486e358ae6a319c5206',
    messagingSenderId: '437896099955',
    projectId: 'messenger-8de19',
    authDomain: 'messenger-8de19.firebaseapp.com',
    storageBucket: 'messenger-8de19.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrNHuBVI4NzFsh4-xEQVODEOV5L_2wWSM',
    appId: '1:437896099955:android:c6ff13b8cb3506f49c5206',
    messagingSenderId: '437896099955',
    projectId: 'messenger-8de19',
    storageBucket: 'messenger-8de19.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGoPjQ_0s6MpolWO3O_16kmuTW9fLmyac',
    appId: '1:437896099955:ios:78cfe4279b18fdd09c5206',
    messagingSenderId: '437896099955',
    projectId: 'messenger-8de19',
    storageBucket: 'messenger-8de19.firebasestorage.app',
    iosBundleId: 'com.wisedev.messenger',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoj5K9FsCMTsOOBlMQXjPHeIR-IPZxJIM',
    appId: '1:437896099955:web:95722a78f4acc3649c5206',
    messagingSenderId: '437896099955',
    projectId: 'messenger-8de19',
    authDomain: 'messenger-8de19.firebaseapp.com',
    storageBucket: 'messenger-8de19.firebasestorage.app',
  );
}
